@startuml DataModel
object Note {
  _id: ObjectId
  title: String
  content: String
  tags: Array<String>
  createdAt: Date
}

object Comment {
  content: String
  createdAt: Date
}

Note *-- Comment : "Embedded (1:N)"
@enduml
